version: '3'

services:
  app:
    build: .
    container_name: challengeFS
    environment:
      - SPRING_DATA_MYSQL_URI=jdbc:mysql://db:3306/fourSales
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - foursales-net
  db:
    container_name: challengeFS-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fourSales
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - database
    networks:
      - foursales-net
networks:
  foursales-net:
    name: db-net
    driver: bridge